-- Seed data generated from data.js — JAMMIN JUNCTION
-- Safe to re-run: clears tables first.
truncate table public.items;
delete from public.sections;

insert into public.sections (menu_type,category,sub_category,display_name,image_url,sort_order) values
('regular','food',null,'food','assets/cat/food.jpg',0),
('regular','food','SOUPS','SOUPS','assets/food/soups.jpg',0),
('regular','food','SALAD','SALAD','assets/food/salad.jpg',1),
('regular','food','ALCOHOL BASED STARTERS','ALCOHOL BASED STARTERS','assets/food/alcohol_starters.png',2),
('regular','food','CHINESE STARTERS','CHINESE STARTERS','assets/food/chinese_starters.jpg',3),
('regular','food','CHINESE MAIN COURSE','CHINESE MAIN COURSE','assets/food/chinese_main.jpg',4),
('regular','food','VEG CONTINENTAL','VEG CONTINENTAL','assets/food/veg_continental.jpg',5),
('regular','food','NON-VEG CONTINENTAL','NON-VEG CONTINENTAL','assets/food/nonveg_continental.jpg',6),
('regular','food','CONTINENTAL MAIN COURSE','CONTINENTAL MAIN COURSE','assets/food/continental_main.png',7),
('regular','food','PIZZA','PIZZA','assets/food/pizza.jpg',8),
('regular','food','SANDWICH','SANDWICH','assets/food/sandwich.jpg',9),
('regular','food','MINI BURGERS','MINI BURGERS','assets/food/mini_burgers.jpg',10),
('regular','food','PASTA','PASTA','assets/food/pasta.jpg',11),
('regular','food','FRIES','FRIES','assets/food/fries.jpg',12),
('regular','food','TANDOORI BHATTI STARTERS','TANDOORI BHATTI STARTERS','assets/food/tandoori.jpg',13),
('regular','food','BREADS','BREADS','assets/food/breads.jpg',14),
('regular','food','PAPAD','PAPAD','assets/food/papad.jpg',15),
('regular','food','SOUTH INDIAN STARTERS','SOUTH INDIAN STARTERS','assets/food/south_indian.jpg',16),
('regular','food','INDIAN CURRIES','INDIAN CURRIES','assets/food/indian_curries.jpg',17),
('regular','food','PULAV / BIRYANI','PULAV / BIRYANI','assets/food/pulav_biryani.jpg',18),
('regular','food','RICE','RICE','assets/food/rice.jpg',19),
('regular','drinks',null,'drinks','assets/cat/drinks.jpg',1),
('regular','drinks','BEER','BEER','assets/drinks/beer.jpg',0),
('regular','drinks','BREEZER','BREEZER','assets/drinks/breezer.png',1),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','assets/drinks/scotch.png',2),
('regular','drinks','RUM','RUM','assets/drinks/rum.jpg',3),
('regular','drinks','VODKA','VODKA','assets/drinks/vodka.jpg',4),
('regular','drinks','GIN','GIN','assets/drinks/gin.jpg',5),
('regular','drinks','TEQUILA','TEQUILA','assets/drinks/tequila.jpg',6),
('regular','drinks','RED WINE','RED WINE','assets/drinks/red_wine.jpg',7),
('regular','drinks','WHITE WINE','WHITE WINE','assets/drinks/white_wine.jpg',8),
('regular','drinks','ROSE WINE','ROSE WINE','assets/drinks/rose_wine.jpg',9),
('regular','drinks','BRUT & SPARKLING','BRUT & SPARKLING','assets/drinks/brut.jpg',10),
('regular','drinks','SHOOTER''S','SHOOTER''S','assets/drinks/shooters.jpg',11),
('regular','drinks','LIQUEURS','LIQUEURS','assets/drinks/liqueurs.jpg',12),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','JAMMIN SIGNATURE COCKTAILS','assets/drinks/jammin_cocktails.png',13),
('regular','drinks','COCKTAILS','COCKTAILS','assets/drinks/cocktails.jpg',14),
('regular','drinks','CLASSIC COCKTAILS','CLASSIC COCKTAILS','assets/drinks/classic_cocktails.jpg',15),
('regular','beverages',null,'beverages','assets/cat/beverages.jpg',2),
('regular','beverages','FRESH JUICE','FRESH JUICE','assets/beverages/fresh_juice.jpg',0),
('regular','beverages','MOCKTAIL','MOCKTAIL','assets/beverages/mocktail.jpg',1),
('regular','beverages','SOFT BEVERAGE','SOFT BEVERAGE','assets/beverages/soft_beverage.jpg',2),
('regular','desserts',null,'desserts','assets/cat/desserts.jpg',3),
('regular','desserts','DESSERT','DESSERT','assets/desserts/dessert.jpg',0),
('happy','happy hours food',null,'happy hours food','assets/cat/hh_food.jpg',0),
('happy','happy hours food','VEG STARTERS','VEG STARTERS','assets/hh_food/veg_starters.jpg',0),
('happy','happy hours food','NON VEG STARTERS','NON VEG STARTERS','assets/hh_food/nonveg_starters.jpg',1),
('happy','happy hours food','PIZZA','PIZZA','assets/hh_food/pizza.png',2),
('happy','happy hours food','BREAD / RICE','BREAD / RICE','assets/hh_food/bread_rice.png',3),
('happy','happy hours food','CURRIES','CURRIES','assets/hh_food/curries.jpg',4),
('happy','happy hours food','COMBO','COMBO','assets/hh_food/combo.jpg',5),
('happy','happy hours drinks',null,'happy hours drinks','assets/cat/hh_drinks.jpg',1),
('happy','happy hours drinks','LIQUOR','LIQUOR','assets/hh_drinks/liquor.jpg',0),
('happy','happy hours drinks','COCKTAILS','COCKTAILS','assets/hh_drinks/cocktails.png',1),
('happy','happy hours drinks','MOCKTAILS / JUICE','MOCKTAILS / JUICE','assets/hh_drinks/mocktails.png',2);

insert into public.items (menu_type,category,sub_category,name,item_type,price,qty,image_url,priority,is_active) values
('regular','food','SOUPS','VEG MANCHOW SOUP','veg',249,'{}'::jsonb,'',0,true),
('regular','food','SOUPS','NON-VEG MANCHOW SOUP','non-veg',249,'{}'::jsonb,'',1,true),
('regular','food','SOUPS','VEG SWEET CORN SOUP','veg',249,'{}'::jsonb,'',2,true),
('regular','food','SOUPS','NON-VEG SWEET CORN SOUP','non-veg',249,'{}'::jsonb,'',3,true),
('regular','food','SOUPS','VEG HOT AND SOUR SOUP','veg',249,'{}'::jsonb,'',4,true),
('regular','food','SOUPS','NON-VEG HOT AND SOUR SOUP','non-veg',299,'{}'::jsonb,'',5,true),
('regular','food','SOUPS','TOM YUM NON-VEG SOUP','non-veg',249,'{}'::jsonb,'',6,true),
('regular','food','SOUPS','MUTTON PAYA SOUP','non-veg',349,'{}'::jsonb,'',7,true),
('regular','food','SALAD','WATERMELON FETA CHEESE','veg',399,'{}'::jsonb,'',0,true),
('regular','food','SALAD','VEG CAESAR SALAD','veg',199,'{}'::jsonb,'',1,true),
('regular','food','SALAD','NON-VEG CAESAR SALAD','non-veg',299,'{}'::jsonb,'',2,true),
('regular','food','SALAD','GREEN SALAD','veg',249,'{}'::jsonb,'',3,true),
('regular','food','SALAD','CHICKEN PEANUT SALAD','non-veg',399,'{}'::jsonb,'',4,true),
('regular','food','ALCOHOL BASED STARTERS','RUM KA CHICKEN','non-veg',799,'{}'::jsonb,'',0,true),
('regular','food','ALCOHOL BASED STARTERS','SCALLION BRANDY CHICKEN','non-veg',799,'{}'::jsonb,'',1,true),
('regular','food','ALCOHOL BASED STARTERS','CAJUN SPICY BEER BATTER FISH','seafood',799,'{}'::jsonb,'',2,true),
('regular','food','CHINESE STARTERS','CRISPY CHILLI CORN','veg',499,'{}'::jsonb,'',0,true),
('regular','food','CHINESE STARTERS','CRISPY WATER CHESTNUT LOTUS STEM','veg',499,'{}'::jsonb,'',1,true),
('regular','food','CHINESE STARTERS','KOREAN POPCORN CAULIFLOWER','veg',499,'{}'::jsonb,'',2,true),
('regular','food','CHINESE STARTERS','HOT BASIL PANEER IN RED CHILLI SAUCE','veg',499,'{}'::jsonb,'',3,true),
('regular','food','CHINESE STARTERS','PANEER 65','veg',499,'{}'::jsonb,'',4,true),
('regular','food','CHINESE STARTERS','CHILLI PANEER','veg',499,'{}'::jsonb,'',5,true),
('regular','food','CHINESE STARTERS','BURMESE CHEESE ROLL','veg',499,'{}'::jsonb,'',6,true),
('regular','food','CHINESE STARTERS','KUNG PAO CHICKEN','non-veg',599,'{}'::jsonb,'',7,true),
('regular','food','CHINESE STARTERS','HOT PEPPER BASIL CHICKEN','non-veg',599,'{}'::jsonb,'',8,true),
('regular','food','CHINESE STARTERS','CHILLI CHICKEN','non-veg',599,'{}'::jsonb,'',9,true),
('regular','food','CHINESE STARTERS','CHICKEN 65','non-veg',599,'{}'::jsonb,'',10,true),
('regular','food','CHINESE STARTERS','CHICKEN MAJESTIC','non-veg',599,'{}'::jsonb,'',11,true),
('regular','food','CHINESE STARTERS','KOREAN STYLE CHICKEN','non-veg',599,'{}'::jsonb,'',12,true),
('regular','food','CHINESE STARTERS','CHICKEN SKEWER LEMONGRASS','non-veg',599,'{}'::jsonb,'',13,true),
('regular','food','CHINESE STARTERS','CRISPY FRIED CARAMEL PRAWNS','seafood',699,'{}'::jsonb,'',14,true),
('regular','food','CHINESE STARTERS','LOOSE PRAWN','seafood',699,'{}'::jsonb,'',15,true),
('regular','food','CHINESE STARTERS','DYNAMITE PRAWNS','seafood',749,'{}'::jsonb,'',16,true),
('regular','food','CHINESE STARTERS','CHILLI PRAWNS','seafood',749,'{}'::jsonb,'',17,true),
('regular','food','CHINESE STARTERS','CHILLI FISH','seafood',749,'{}'::jsonb,'',18,true),
('regular','food','CHINESE STARTERS','APOLLO FISH','seafood',749,'{}'::jsonb,'',19,true),
('regular','food','CHINESE STARTERS','OYSTER CHILLI FISH','seafood',699,'{}'::jsonb,'',20,true),
('regular','food','CHINESE MAIN COURSE','VEG CHILLI GARLIC FRIED RICE','veg',449,'{}'::jsonb,'',0,true),
('regular','food','CHINESE MAIN COURSE','NON-VEG CHILLI GARLIC FRIED RICE','non-veg',499,'{}'::jsonb,'',1,true),
('regular','food','CHINESE MAIN COURSE','VEG SCHEZWAN FRIED RICE','veg',449,'{}'::jsonb,'',2,true),
('regular','food','CHINESE MAIN COURSE','NON-VEG SCHEZWAN FRIED RICE','non-veg',499,'{}'::jsonb,'',3,true),
('regular','food','CHINESE MAIN COURSE','VEG SINGAPORE NOODLES','veg',449,'{}'::jsonb,'',4,true),
('regular','food','CHINESE MAIN COURSE','NON-VEG SINGAPOREAN NOODLES','non-veg',499,'{}'::jsonb,'',5,true),
('regular','food','CHINESE MAIN COURSE','VEG PAD THAI NOODLES','veg',449,'{}'::jsonb,'',6,true),
('regular','food','CHINESE MAIN COURSE','NON-VEG PAD THAI NOODLES','non-veg',499,'{}'::jsonb,'',7,true),
('regular','food','CHINESE MAIN COURSE','VEG CHILLI GARLIC NOODLES','veg',449,'{}'::jsonb,'',8,true),
('regular','food','CHINESE MAIN COURSE','NON-VEG CHILLI GARLIC NOODLES','non-veg',499,'{}'::jsonb,'',9,true),
('regular','food','CHINESE MAIN COURSE','VEG THAI RED CURRY WITH JASMINE RICE','veg',699,'{}'::jsonb,'',10,true),
('regular','food','CHINESE MAIN COURSE','NON-VEG THAI RED CURRY WITH JASMINE RICE','non-veg',699,'{}'::jsonb,'',11,true),
('regular','food','CHINESE MAIN COURSE','VEG THAI GREEN CURRY WITH JASMINE RICE','veg',699,'{}'::jsonb,'',12,true),
('regular','food','CHINESE MAIN COURSE','NON-VEG THAI GREEN CURRY WITH JASMINE RICE','non-veg',699,'{}'::jsonb,'',13,true),
('regular','food','CHINESE MAIN COURSE','KOREAN BLACK BEAN PAD THAI NOODLES','veg',699,'{}'::jsonb,'',14,true),
('regular','food','VEG CONTINENTAL','PANEER POPCORN','veg',599,'{}'::jsonb,'',0,true),
('regular','food','VEG CONTINENTAL','PANEER SKEWERS','veg',549,'{}'::jsonb,'',1,true),
('regular','food','VEG CONTINENTAL','JALAPENO CHEESE BALL','veg',599,'{}'::jsonb,'',2,true),
('regular','food','VEG CONTINENTAL','CLASSIC VEG CHEESE PEPPER','veg',549,'{}'::jsonb,'',3,true),
('regular','food','VEG CONTINENTAL','ONION RINGS','veg',549,'{}'::jsonb,'',4,true),
('regular','food','VEG CONTINENTAL','VEG NACHOS','veg',549,'{}'::jsonb,'',5,true),
('regular','food','NON-VEG CONTINENTAL','NON-VEG NACHOS','non-veg',549,'{}'::jsonb,'',0,true),
('regular','food','NON-VEG CONTINENTAL','CHICKEN POPCORN','non-veg',649,'{}'::jsonb,'',1,true),
('regular','food','NON-VEG CONTINENTAL','CRISPY FRIED CHICKEN NUGGETS','non-veg',599,'{}'::jsonb,'',2,true),
('regular','food','NON-VEG CONTINENTAL','SMOKY CHICKEN SKEWERS','non-veg',599,'{}'::jsonb,'',3,true),
('regular','food','NON-VEG CONTINENTAL','VIETNAMESE GRILLED PRAWNS','seafood',699,'{}'::jsonb,'',4,true),
('regular','food','NON-VEG CONTINENTAL','CILANTRO FISH BITES','seafood',699,'{}'::jsonb,'',5,true),
('regular','food','NON-VEG CONTINENTAL','FISH FINGERS','seafood',699,'{}'::jsonb,'',6,true),
('regular','food','CONTINENTAL MAIN COURSE','CAPRESE COTTAGE CHEESE STUFFED','veg',699,'{}'::jsonb,'',0,true),
('regular','food','CONTINENTAL MAIN COURSE','ASPARAGUS CHICKEN ROLADA','non-veg',699,'{}'::jsonb,'',1,true),
('regular','food','CONTINENTAL MAIN COURSE','GRILLED SEA BASS','seafood',799,'{}'::jsonb,'',2,true),
('regular','food','PIZZA','MARGHERITA PIZZA','veg',499,'{}'::jsonb,'',0,true),
('regular','food','PIZZA','GARDEN VEG PIZZA','veg',499,'{}'::jsonb,'',1,true),
('regular','food','PIZZA','PANEER TIKKA PIZZA','veg',499,'{}'::jsonb,'',2,true),
('regular','food','PIZZA','CHICKEN TIKKA PIZZA','non-veg',699,'{}'::jsonb,'',3,true),
('regular','food','PIZZA','BARBEQUE CHICKEN PIZZA','non-veg',699,'{}'::jsonb,'',4,true),
('regular','food','SANDWICH','VEG CLUB SANDWICH','veg',399,'{}'::jsonb,'',0,true),
('regular','food','SANDWICH','CHICKEN CLUB SANDWICH','non-veg',449,'{}'::jsonb,'',1,true),
('regular','food','MINI BURGERS','CRACKER CHICKEN BURGER','non-veg',499,'{}'::jsonb,'',0,true),
('regular','food','MINI BURGERS','COTTAGE CHEESE BURGER','veg',449,'{}'::jsonb,'',1,true),
('regular','food','PASTA','VEG PENNE PASTA WHITE SAUCE','veg',649,'{}'::jsonb,'',0,true),
('regular','food','PASTA','VEG PENNE PASTA RED SAUCE','veg',599,'{}'::jsonb,'',1,true),
('regular','food','PASTA','NON-VEG PENNE PASTA WHITE SAUCE','non-veg',749,'{}'::jsonb,'',2,true),
('regular','food','PASTA','NON-VEG PENNE PASTA RED SAUCE','non-veg',699,'{}'::jsonb,'',3,true),
('regular','food','PASTA','VEG SPAGHETTI WHITE SAUCE','veg',599,'{}'::jsonb,'',4,true),
('regular','food','PASTA','VEG SPAGHETTI RED SAUCE','veg',599,'{}'::jsonb,'',5,true),
('regular','food','PASTA','VEG SPAGHETTI CREAMY PESTO','veg',599,'{}'::jsonb,'',6,true),
('regular','food','PASTA','NON-VEG SPAGHETTI WHITE SAUCE','non-veg',699,'{}'::jsonb,'',7,true),
('regular','food','PASTA','NON-VEG SPAGHETTI RED SAUCE','non-veg',699,'{}'::jsonb,'',8,true),
('regular','food','PASTA','NON-VEG SPAGHETTI CREAMY PESTO','non-veg',699,'{}'::jsonb,'',9,true),
('regular','food','FRIES','PERI PERI FRENCH FRIES','veg',499,'{}'::jsonb,'',0,true),
('regular','food','FRIES','SALTED FRENCH FRIES','veg',399,'{}'::jsonb,'',1,true),
('regular','food','FRIES','SALTED POTATO WEDGES','veg',499,'{}'::jsonb,'',2,true),
('regular','food','FRIES','MASALA POTATO WEDGES','veg',499,'{}'::jsonb,'',3,true),
('regular','food','FRIES','PEANUT MASALA','veg',399,'{}'::jsonb,'',4,true),
('regular','food','FRIES','SALTED CASHEW FRY','veg',599,'{}'::jsonb,'',5,true),
('regular','food','FRIES','MASALA CASHEW FRY','veg',599,'{}'::jsonb,'',6,true),
('regular','food','TANDOORI BHATTI STARTERS','KARARI VEG TIKKI','veg',499,'{}'::jsonb,'',0,true),
('regular','food','TANDOORI BHATTI STARTERS','PAHADI PANEER TIKKA','veg',549,'{}'::jsonb,'',1,true),
('regular','food','TANDOORI BHATTI STARTERS','PUDINA BISAIL PANEER TIKKA','veg',499,'{}'::jsonb,'',2,true),
('regular','food','TANDOORI BHATTI STARTERS','JAMINDARI MUSHROOM','veg',499,'{}'::jsonb,'',3,true),
('regular','food','TANDOORI BHATTI STARTERS','MALAI BROCCOLI','veg',499,'{}'::jsonb,'',4,true),
('regular','food','TANDOORI BHATTI STARTERS','MURGH MALAI KEBAB','non-veg',659,'{}'::jsonb,'',5,true),
('regular','food','TANDOORI BHATTI STARTERS','R.C. CHICKEN TIKKA','non-veg',599,'{}'::jsonb,'',6,true),
('regular','food','TANDOORI BHATTI STARTERS','PERI PERI CHICKEN TIKKA','non-veg',699,'{}'::jsonb,'',7,true),
('regular','food','TANDOORI BHATTI STARTERS','CHICKEN TANGDI KEBAB','non-veg',599,'{}'::jsonb,'',8,true),
('regular','food','TANDOORI BHATTI STARTERS','MUTTON SRIRACHA CHOP','non-veg',699,'{}'::jsonb,'',9,true),
('regular','food','TANDOORI BHATTI STARTERS','TANDOORI PERI PERI PRAWNS','seafood',699,'{}'::jsonb,'',10,true),
('regular','food','TANDOORI BHATTI STARTERS','MIRYALA PRAWNS','seafood',699,'{}'::jsonb,'',11,true),
('regular','food','TANDOORI BHATTI STARTERS','TANDOORI FISH TIKKA','seafood',789,'{}'::jsonb,'',12,true),
('regular','food','TANDOORI BHATTI STARTERS','AMRITSARI FISH TIKKA','seafood',789,'{}'::jsonb,'',13,true),
('regular','food','BREADS','TANDOORI ROTI','veg',99,'{}'::jsonb,'',0,true),
('regular','food','BREADS','PLAIN NAAN','veg',99,'{}'::jsonb,'',1,true),
('regular','food','BREADS','PLAIN ROTI','veg',99,'{}'::jsonb,'',2,true),
('regular','food','BREADS','LACHHA PARATHA','veg',99,'{}'::jsonb,'',3,true),
('regular','food','BREADS','GARLIC NAAN','veg',99,'{}'::jsonb,'',4,true),
('regular','food','PAPAD','ROASTED PAPAD','veg',99,'{"2 PCS":"99"}'::jsonb,'',0,true),
('regular','food','PAPAD','MASALA PAPAD','veg',149,'{}'::jsonb,'',1,true),
('regular','food','SOUTH INDIAN STARTERS','PACHI MIRCHI PANEER VEPUDU','veg',499,'{}'::jsonb,'',0,true),
('regular','food','SOUTH INDIAN STARTERS','MOKKAJONNA VADA','veg',499,'{}'::jsonb,'',1,true),
('regular','food','SOUTH INDIAN STARTERS','JEEDI PAPPU MUSHROOM VEPUDU','veg',499,'{}'::jsonb,'',2,true),
('regular','food','SOUTH INDIAN STARTERS','JEEDI PAPPU KODI VEPUDU','non-veg',699,'{}'::jsonb,'',3,true),
('regular','food','SOUTH INDIAN STARTERS','KOTHIMEERA KODI VEPUDU','non-veg',599,'{}'::jsonb,'',4,true),
('regular','food','SOUTH INDIAN STARTERS','GHEE ROAST KODI VEPUDU','non-veg',699,'{}'::jsonb,'',5,true),
('regular','food','SOUTH INDIAN STARTERS','JEEDI PAPPU KODI PAKODA','non-veg',599,'{}'::jsonb,'',6,true),
('regular','food','SOUTH INDIAN STARTERS','MUTTON GHEE ROAST','non-veg',789,'{}'::jsonb,'',7,true),
('regular','food','SOUTH INDIAN STARTERS','VELLUPAYA KARAM ROYALU','seafood',699,'{}'::jsonb,'',8,true),
('regular','food','SOUTH INDIAN STARTERS','NALLA KARAM ROYALU VEPUDU','seafood',699,'{}'::jsonb,'',9,true),
('regular','food','SOUTH INDIAN STARTERS','RAWA FISH FRY','seafood',699,'{}'::jsonb,'',10,true),
('regular','food','SOUTH INDIAN STARTERS','TAWA FISH FRY','seafood',699,'{}'::jsonb,'',11,true),
('regular','food','INDIAN CURRIES','MIX VEG CURRY','veg',449,'{}'::jsonb,'',0,true),
('regular','food','INDIAN CURRIES','PANEER BUTTER MASALA','veg',499,'{}'::jsonb,'',1,true),
('regular','food','INDIAN CURRIES','KADAI PANEER','veg',499,'{}'::jsonb,'',2,true),
('regular','food','INDIAN CURRIES','PALAK PANEER','veg',499,'{}'::jsonb,'',3,true),
('regular','food','INDIAN CURRIES','CHICKEN BUTTER MASALA','non-veg',599,'{}'::jsonb,'',4,true),
('regular','food','INDIAN CURRIES','CHICKEN TIKKA MASALA','non-veg',599,'{}'::jsonb,'',5,true),
('regular','food','INDIAN CURRIES','TELANGANA SPICY CHICKEN CURRY','non-veg',659,'{}'::jsonb,'',6,true),
('regular','food','INDIAN CURRIES','KODI KURRA','non-veg',599,'{}'::jsonb,'',7,true),
('regular','food','INDIAN CURRIES','GONGURA MUTTON CURRY','non-veg',759,'{}'::jsonb,'',8,true),
('regular','food','INDIAN CURRIES','MUTTON ROGAN JOSH','non-veg',759,'{}'::jsonb,'',9,true),
('regular','food','INDIAN CURRIES','MUTTON KEEMA CURRY','non-veg',759,'{}'::jsonb,'',10,true),
('regular','food','INDIAN CURRIES','TELANGANA GUDDU KURRA','egg',599,'{}'::jsonb,'',11,true),
('regular','food','PULAV / BIRYANI','VEG PULAO','veg',499,'{}'::jsonb,'',0,true),
('regular','food','PULAV / BIRYANI','PACHI MIRCHI PANEER PULAO','veg',499,'{}'::jsonb,'',1,true),
('regular','food','PULAV / BIRYANI','CHITTI MUTHYALU VEG PULAO','veg',499,'{}'::jsonb,'',2,true),
('regular','food','PULAV / BIRYANI','PACHIMIRCHI KODI PULAO','non-veg',699,'{}'::jsonb,'',3,true),
('regular','food','PULAV / BIRYANI','RAJU GARI KODI PULAO','non-veg',699,'{}'::jsonb,'',4,true),
('regular','food','PULAV / BIRYANI','BHIMAVARAM KODI PULAO','non-veg',699,'{}'::jsonb,'',5,true),
('regular','food','PULAV / BIRYANI','ROYALU VEPUDU PULAO','seafood',599,'{}'::jsonb,'',6,true),
('regular','food','PULAV / BIRYANI','CHITTI MUTHYALLU ROYALU PULAO','seafood',599,'{}'::jsonb,'',7,true),
('regular','food','PULAV / BIRYANI','MUTTON GHEE ROAST PULAO','non-veg',599,'{}'::jsonb,'',8,true),
('regular','food','PULAV / BIRYANI','MASTANI KEEMA PULAO','non-veg',599,'{}'::jsonb,'',9,true),
('regular','food','PULAV / BIRYANI','CHICKEN DUM BIRYANI','non-veg',599,'{}'::jsonb,'',10,true),
('regular','food','RICE','SAMBAR RICE WITH ALOO FRY','veg',499,'{}'::jsonb,'',0,true),
('regular','food','RICE','SAMBAR RICE WITH CHICKEN FRY','non-veg',499,'{}'::jsonb,'',1,true),
('regular','food','RICE','CURD RICE WITH PICKLE','veg',459,'{}'::jsonb,'',2,true),
('regular','food','RICE','JEERA RICE','veg',399,'{}'::jsonb,'',3,true),
('regular','food','RICE','PLAIN RICE','veg',249,'{}'::jsonb,'',4,true),
('regular','drinks','BEER','KINGFISHER DRAUGHT','alcoholic',349,'{"GLASS":"349","PITCHER":"1399","TOWER":"2699"}'::jsonb,'',0,true),
('regular','drinks','BEER','HOEGAARDEN','alcoholic',699,'{"PINTS":"699","BUCKET OF 6":"3899"}'::jsonb,'',1,true),
('regular','drinks','BEER','CORONA','alcoholic',699,'{"PINTS":"699","BUCKET OF 6":"3899"}'::jsonb,'',2,true),
('regular','drinks','BEER','BIRA WHITE','alcoholic',549,'{"PINTS":"549","BUCKET OF 6":"2749"}'::jsonb,'',3,true),
('regular','drinks','BEER','BUDWEISER','alcoholic',549,'{"PINTS":"549","BUCKET OF 6":"2999"}'::jsonb,'',4,true),
('regular','drinks','BEER','HEINEKEN','alcoholic',499,'{"PINTS":"499","BUCKET OF 6":"2699"}'::jsonb,'',5,true),
('regular','drinks','BEER','KINGFISHER ULTRA','alcoholic',499,'{"PINTS":"499","BUCKET OF 6":"2799"}'::jsonb,'',6,true),
('regular','drinks','BREEZER','BREEZER ALL FLAVOURS','alcoholic',399,'{"BOTTLE":"399","BUCKET OF 6":"2199"}'::jsonb,'',0,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','ADMORE','alcoholic',699,'{"30 ML":"699","BOTTLE":"13999"}'::jsonb,'',0,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','GLENLIVET 12 YRS','alcoholic',849,'{"30 ML":"849","BOTTLE":"15999"}'::jsonb,'',1,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','ABERFELDY 12 YRS','alcoholic',799,'{"30 ML":"799","BOTTLE":"15999"}'::jsonb,'',2,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','AMRUT FUSION','alcoholic',599,'{"30 ML":"599","BOTTLE":"12999"}'::jsonb,'',3,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','MONKEY SHOULDER','alcoholic',599,'{"30 ML":"599","BOTTLE":"12999"}'::jsonb,'',4,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','JW BLACK LABEL','alcoholic',599,'{"30 ML":"599","BOTTLE":"12999"}'::jsonb,'',5,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','CHIVAS 12 YRS','alcoholic',649,'{"30 ML":"649","BOTTLE":"13999"}'::jsonb,'',6,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','TEACHERS 50','alcoholic',599,'{"30 ML":"599","BOTTLE":"12999"}'::jsonb,'',7,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','100 PIPERS 08 YRS','alcoholic',499,'{"30 ML":"499","BOTTLE":"8999"}'::jsonb,'',8,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','BALLANTINE FINEST','alcoholic',499,'{"30 ML":"499","BOTTLE":"8999"}'::jsonb,'',9,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','BLACK & WHITE','alcoholic',499,'{"30 ML":"499","BOTTLE":"8999"}'::jsonb,'',10,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','JIM BEAM','alcoholic',599,'{"30 ML":"599","BOTTLE":"11999"}'::jsonb,'',11,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','JACK DANIELS','alcoholic',649,'{"30 ML":"649","BOTTLE":"12999"}'::jsonb,'',12,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','JAMESON','alcoholic',699,'{"30 ML":"699","BOTTLE":"14999"}'::jsonb,'',13,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','BUSHMILLS','alcoholic',599,'{"30 ML":"599","BOTTLE":"11999"}'::jsonb,'',14,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','PAUL JOHN','alcoholic',599,'{"30 ML":"599","BOTTLE":"11999"}'::jsonb,'',15,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','DEWARS WHITE LABEL','alcoholic',649,'{"30 ML":"649","BOTTLE":"9999"}'::jsonb,'',16,true),
('regular','drinks','SCOTCH/BLENDED/BOURBON/IRISH WHISKEY','TEACHERS ISLAND','alcoholic',499,'{"30 ML":"499","BOTTLE":"9999"}'::jsonb,'',17,true),
('regular','drinks','RUM','KYRON','alcoholic',399,'{"30 ML":"399","BOTTLE":"5999"}'::jsonb,'',0,true),
('regular','drinks','RUM','BACARDI WHITE','alcoholic',349,'{"30 ML":"349","BOTTLE":"5999"}'::jsonb,'',1,true),
('regular','drinks','RUM','OLD MONK','alcoholic',349,'{"30 ML":"349","BOTTLE":"5999"}'::jsonb,'',2,true),
('regular','drinks','VODKA','SANTORY HAKU','alcoholic',849,'{"30 ML":"849","BOTTLE":"17999"}'::jsonb,'',0,true),
('regular','drinks','VODKA','GREY GOOSE','alcoholic',599,'{"30 ML":"599","BOTTLE":"12999"}'::jsonb,'',1,true),
('regular','drinks','VODKA','ABSOLUTE','alcoholic',549,'{"30 ML":"549","BOTTLE":"10999"}'::jsonb,'',2,true),
('regular','drinks','GIN','ROKU','alcoholic',799,'{"30 ML":"799","BOTTLE":"15999"}'::jsonb,'',0,true),
('regular','drinks','GIN','HENDRICK''S','alcoholic',699,'{"30 ML":"699","BOTTLE":"13999"}'::jsonb,'',1,true),
('regular','drinks','GIN','JAISALMER','alcoholic',599,'{"30 ML":"599","BOTTLE":"11999"}'::jsonb,'',2,true),
('regular','drinks','GIN','BOMBAY SAPPHIRE','alcoholic',499,'{"30 ML":"499","BOTTLE":"10999"}'::jsonb,'',3,true),
('regular','drinks','TEQUILA','DESMONDJI 51 AGAVE','alcoholic',449,'{"30 ML":"449","BOTTLE":"6999"}'::jsonb,'',0,true),
('regular','drinks','TEQUILA','JOSE CUERVO SILVER','alcoholic',599,'{"30 ML":"599","BOTTLE":"12999"}'::jsonb,'',1,true),
('regular','drinks','TEQUILA','JOSE CUERVO GOLD','alcoholic',499,'{"30 ML":"499","BOTTLE":"9999"}'::jsonb,'',2,true),
('regular','drinks','RED WINE','CASACA CABERNET MERLOT','alcoholic',999,'{"30 ML":"999","BOTTLE":"6999"}'::jsonb,'',0,true),
('regular','drinks','RED WINE','J.C SHIRAZ','alcoholic',999,'{"30 ML":"999","BOTTLE":"4999"}'::jsonb,'',1,true),
('regular','drinks','RED WINE','SULA SHIRAZ','alcoholic',799,'{"30 ML":"799","BOTTLE":"3499"}'::jsonb,'',2,true),
('regular','drinks','WHITE WINE','J.C CHARDONNAY','alcoholic',949,'{"30 ML":"949","BOTTLE":"5799"}'::jsonb,'',0,true),
('regular','drinks','WHITE WINE','SULA CHENIN BLANC','alcoholic',649,'{"150 ML":"649","BOTTLE":"3299"}'::jsonb,'',1,true),
('regular','drinks','ROSE WINE','PINK TWINKLE','alcoholic',1499,'{"30 ML":"1499","BOTTLE":"7999"}'::jsonb,'',0,true),
('regular','drinks','ROSE WINE','SULA ZINFANDEL ROSE','alcoholic',699,'{"30 ML":"699","BOTTLE":"3999"}'::jsonb,'',1,true),
('regular','drinks','BRUT & SPARKLING','SULA BRUT','alcoholic',899,'{"30 ML":"899","BOTTLE":"4999"}'::jsonb,'',0,true),
('regular','drinks','BRUT & SPARKLING','CHANDON BRUT','alcoholic',899,'{"30 ML":"899","BOTTLE":"4999"}'::jsonb,'',1,true),
('regular','drinks','BRUT & SPARKLING','J.C SPARKLING ROSE','alcoholic',949,'{"30 ML":"949","BOTTLE":"5999"}'::jsonb,'',2,true),
('regular','drinks','SHOOTER''S','JAGER ENERGY','alcoholic',899,'{}'::jsonb,'',0,true),
('regular','drinks','SHOOTER''S','KAMIKAZE','alcoholic',499,'{}'::jsonb,'',1,true),
('regular','drinks','SHOOTER''S','BAILEYS.','alcoholic',549,'{}'::jsonb,'',2,true),
('regular','drinks','SHOOTER''S','FLAMING LAMBORGHINI','alcoholic',1799,'{}'::jsonb,'',3,true),
('regular','drinks','LIQUEURS','JAGERMEISTER','alcoholic',699,'{"30 ML":"699","BOTTLE":"13999"}'::jsonb,'',0,true),
('regular','drinks','LIQUEURS','BAILEYS','alcoholic',549,'{"30 ML":"549","BOTTLE":"12999"}'::jsonb,'',1,true),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','ROOT TO FRUITS','alcoholic',649,'{}'::jsonb,'',0,true),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','BLUE BUTTERFLY','alcoholic',649,'{}'::jsonb,'',1,true),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','MYSTIC MULE (CLARIFIED)','alcoholic',599,'{}'::jsonb,'',2,true),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','MANDARIN TIME (INFUSED)','alcoholic',599,'{}'::jsonb,'',3,true),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','SPICY PINO','alcoholic',649,'{}'::jsonb,'',4,true),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','BOOZE VINO','alcoholic',599,'{}'::jsonb,'',5,true),
('regular','drinks','JAMMIN SIGNATURE COCKTAILS','JAMM IN STORY','alcoholic',799,'{"GLASS":"799","PITCHER":"1999"}'::jsonb,'',6,true),
('regular','drinks','COCKTAILS','DAIQUIRI','alcoholic',649,'{}'::jsonb,'',0,true),
('regular','drinks','COCKTAILS','MARGARITA','alcoholic',599,'{}'::jsonb,'',1,true),
('regular','drinks','COCKTAILS','MARTINI (FLAVOURED)','alcoholic',599,'{}'::jsonb,'',2,true),
('regular','drinks','COCKTAILS','COSMOPOLITAN','alcoholic',599,'{}'::jsonb,'',3,true),
('regular','drinks','COCKTAILS','SCREW DRIVER','alcoholic',549,'{"GLASS":"549","PITCHER":"1499"}'::jsonb,'',4,true),
('regular','drinks','COCKTAILS','SEX ON THE BEACH','alcoholic',649,'{}'::jsonb,'',5,true),
('regular','drinks','CLASSIC COCKTAILS','HOT TODDY COCKTAIL','alcoholic',649,'{}'::jsonb,'',0,true),
('regular','drinks','CLASSIC COCKTAILS','MAI TAI COCKTAIL','alcoholic',699,'{}'::jsonb,'',1,true),
('regular','drinks','CLASSIC COCKTAILS','OLD FASHIONED','alcoholic',649,'{}'::jsonb,'',2,true),
('regular','drinks','CLASSIC COCKTAILS','PINA COLADA','alcoholic',699,'{}'::jsonb,'',3,true),
('regular','drinks','CLASSIC COCKTAILS','SANGRIA','alcoholic',649,'{"GLASS":"649","PITCHER":"1699"}'::jsonb,'',4,true),
('regular','drinks','CLASSIC COCKTAILS','MIMOSA','alcoholic',649,'{}'::jsonb,'',5,true),
('regular','drinks','CLASSIC COCKTAILS','WHISKEY SOUR','alcoholic',699,'{}'::jsonb,'',6,true),
('regular','drinks','CLASSIC COCKTAILS','BELLINI','alcoholic',649,'{}'::jsonb,'',7,true),
('regular','drinks','CLASSIC COCKTAILS','LONG ISLAND ICE TEA','alcoholic',899,'{"GLASS":"899","PITCHER":"2499"}'::jsonb,'',8,true),
('regular','drinks','CLASSIC COCKTAILS','LONG ISLAND ICE TEA FLAVORED','alcoholic',999,'{"GLASS":"999","PITCHER":"2599"}'::jsonb,'',9,true),
('regular','beverages','FRESH JUICE','FRESH LIME SODA','non-alcoholic',299,'{}'::jsonb,'',0,true),
('regular','beverages','FRESH JUICE','FRESH LIME WATER','non-alcoholic',249,'{}'::jsonb,'',1,true),
('regular','beverages','FRESH JUICE','WATERMELON','non-alcoholic',299,'{}'::jsonb,'',2,true),
('regular','beverages','FRESH JUICE','MUSKMELON','non-alcoholic',299,'{}'::jsonb,'',3,true),
('regular','beverages','FRESH JUICE','PINE APPLE','non-alcoholic',299,'{}'::jsonb,'',4,true),
('regular','beverages','FRESH JUICE','ORANGE','non-alcoholic',299,'{}'::jsonb,'',5,true),
('regular','beverages','FRESH JUICE','CAN JUICE','non-alcoholic',199,'{}'::jsonb,'',6,true),
('regular','beverages','MOCKTAIL','MOJITO MOCKTAIL','non-alcoholic',399,'{}'::jsonb,'',0,true),
('regular','beverages','MOCKTAIL','VIRGIN PINA COLADA','non-alcoholic',599,'{}'::jsonb,'',1,true),
('regular','beverages','MOCKTAIL','KUKUM KICK','non-alcoholic',399,'{}'::jsonb,'',2,true),
('regular','beverages','MOCKTAIL','HOT TODDY','non-alcoholic',399,'{}'::jsonb,'',3,true),
('regular','beverages','MOCKTAIL','STRAWBERRY SURPRISE','non-alcoholic',399,'{}'::jsonb,'',4,true),
('regular','beverages','MOCKTAIL','JAMM IN PASSION','non-alcoholic',399,'{}'::jsonb,'',5,true),
('regular','beverages','MOCKTAIL','ROSEY DAY','non-alcoholic',399,'{}'::jsonb,'',6,true),
('regular','beverages','MOCKTAIL','LITCHI AAM PANNA','non-alcoholic',399,'{}'::jsonb,'',7,true),
('regular','beverages','MOCKTAIL','PASSION PEACH','non-alcoholic',399,'{}'::jsonb,'',8,true),
('regular','beverages','SOFT BEVERAGE','NYLA AIR WATER','non-alcoholic',199,'{}'::jsonb,'',0,true),
('regular','beverages','SOFT BEVERAGE','PERRIER WATER','non-alcoholic',249,'{}'::jsonb,'',1,true),
('regular','beverages','SOFT BEVERAGE','RED BULL','non-alcoholic',399,'{}'::jsonb,'',2,true),
('regular','beverages','SOFT BEVERAGE','GINGER ALE','non-alcoholic',249,'{}'::jsonb,'',3,true),
('regular','beverages','SOFT BEVERAGE','TONIC WATER','non-alcoholic',249,'{}'::jsonb,'',4,true),
('regular','beverages','SOFT BEVERAGE','DIET COKE','non-alcoholic',249,'{}'::jsonb,'',5,true),
('regular','beverages','SOFT BEVERAGE','THUMS UP','non-alcoholic',249,'{}'::jsonb,'',6,true),
('regular','beverages','SOFT BEVERAGE','SPRITE','non-alcoholic',249,'{}'::jsonb,'',7,true),
('regular','beverages','SOFT BEVERAGE','COKE','non-alcoholic',249,'{}'::jsonb,'',8,true),
('regular','beverages','SOFT BEVERAGE','SODA','non-alcoholic',99,'{"GLASS":"99","BOTTLE":"199"}'::jsonb,'',9,true),
('regular','desserts','DESSERT','GULAB JAMUN','veg',399,'{"3 PCS":"399"}'::jsonb,'',0,true),
('regular','desserts','DESSERT','HOT BROWNIE WITH ICE CREAM','veg',449,'{}'::jsonb,'',1,true),
('regular','desserts','DESSERT','TRES LECHES','veg',499,'{}'::jsonb,'',2,true),
('happy','happy hours food','VEG STARTERS','FRENCH FRIES','veg',199,'{}'::jsonb,'',0,true),
('happy','happy hours food','VEG STARTERS','LALLI PANEER TIKKA','veg',199,'{}'::jsonb,'',1,true),
('happy','happy hours food','VEG STARTERS','AMRITSARI BABY CORN FRY','veg',199,'{}'::jsonb,'',2,true),
('happy','happy hours food','VEG STARTERS','VEG CROQUETTES','veg',199,'{}'::jsonb,'',3,true),
('happy','happy hours food','VEG STARTERS','PANEER TIKKA','veg',199,'{}'::jsonb,'',4,true),
('happy','happy hours food','VEG STARTERS','BABYCORN MUSHROOM','veg',199,'{}'::jsonb,'',5,true),
('happy','happy hours food','VEG STARTERS','CRISPY CORN','veg',199,'{}'::jsonb,'',6,true),
('happy','happy hours food','VEG STARTERS','PANEER 65','veg',199,'{}'::jsonb,'',7,true),
('happy','happy hours food','NON VEG STARTERS','CHILLI CHICKEN','non-veg',199,'{}'::jsonb,'',0,true),
('happy','happy hours food','NON VEG STARTERS','CHICKEN 65','non-veg',199,'{}'::jsonb,'',1,true),
('happy','happy hours food','NON VEG STARTERS','PEPPER CHICKEN','non-veg',199,'{}'::jsonb,'',2,true),
('happy','happy hours food','NON VEG STARTERS','CHICKEN POPCORN','non-veg',199,'{}'::jsonb,'',3,true),
('happy','happy hours food','NON VEG STARTERS','CHICKEN PAKORA','non-veg',199,'{}'::jsonb,'',4,true),
('happy','happy hours food','NON VEG STARTERS','CHICKEN MAJESTIC','non-veg',199,'{}'::jsonb,'',5,true),
('happy','happy hours food','NON VEG STARTERS','CRISPY CHICKEN','non-veg',199,'{}'::jsonb,'',6,true),
('happy','happy hours food','PIZZA','MARGARITA','veg',199,'{"4 PCS":"199"}'::jsonb,'',0,true),
('happy','happy hours food','PIZZA','VEG GARDEN PIZZA','veg',199,'{"4 PCS":"199"}'::jsonb,'',1,true),
('happy','happy hours food','PIZZA','PANEER TIKKA PIZZA','veg',199,'{"4 PCS":"199"}'::jsonb,'',2,true),
('happy','happy hours food','PIZZA','CHICKEN TIKKA PIZZA','non-veg',199,'{"4 PCS":"199"}'::jsonb,'',3,true),
('happy','happy hours food','PIZZA','BARBEQUE CHICKEN PIZZA','non-veg',199,'{"4 PCS":"199"}'::jsonb,'',4,true),
('happy','happy hours food','BREAD / RICE','BUTTER ROTI','veg',49,'{}'::jsonb,'',0,true),
('happy','happy hours food','BREAD / RICE','NAAN','veg',59,'{}'::jsonb,'',1,true),
('happy','happy hours food','BREAD / RICE','BUTTER NAAN','veg',69,'{}'::jsonb,'',2,true),
('happy','happy hours food','BREAD / RICE','VEG PULAV','veg',199,'{}'::jsonb,'',3,true),
('happy','happy hours food','BREAD / RICE','CHICKEN PULAO','non-veg',199,'{}'::jsonb,'',4,true),
('happy','happy hours food','BREAD / RICE','TANDOORI ROTI','veg',39,'{}'::jsonb,'',5,true),
('happy','happy hours food','BREAD / RICE','PLAIN RICE','veg',199,'{}'::jsonb,'',6,true),
('happy','happy hours food','BREAD / RICE','JEERA RICE','veg',199,'{}'::jsonb,'',7,true),
('happy','happy hours food','CURRIES','KADAI PANEER','veg',199,'{}'::jsonb,'',0,true),
('happy','happy hours food','CURRIES','PANEER BUTTER MASALA','veg',199,'{}'::jsonb,'',1,true),
('happy','happy hours food','CURRIES','PANEER CHATPAT','veg',199,'{}'::jsonb,'',2,true),
('happy','happy hours food','CURRIES','PANEER BHURJI MASALA','veg',199,'{}'::jsonb,'',3,true),
('happy','happy hours food','CURRIES','DAL TADKA','veg',199,'{}'::jsonb,'',4,true),
('happy','happy hours food','CURRIES','CHICKEN MASALA','non-veg',199,'{}'::jsonb,'',5,true),
('happy','happy hours food','CURRIES','TELANGANA SPICY CHICKEN','non-veg',199,'{}'::jsonb,'',6,true),
('happy','happy hours food','CURRIES','CHICKEN BUTTER MASALA','non-veg',199,'{}'::jsonb,'',7,true),
('happy','happy hours food','COMBO','BAGARA RICE + MIX VEG CURRY + GREEN SALAD','veg',299,'{}'::jsonb,'',0,true),
('happy','happy hours food','COMBO','SAMABARA RICE + ALOO FRY + PICKLE','veg',299,'{}'::jsonb,'',1,true),
('happy','happy hours food','COMBO','BAGARA RICE + KODI KURRA + GREEN SALAD','non-veg',299,'{}'::jsonb,'',2,true),
('happy','happy hours food','COMBO','SAMBAR RICE + CHICKEN FRY + PICKLE','non-veg',299,'{}'::jsonb,'',3,true),
('happy','happy hours food','COMBO','2 BUTTER NAAN + TELANGANA SPICY CHICKEN CURRY','non-veg',299,'{}'::jsonb,'',4,true),
('happy','happy hours food','COMBO','2 ROTI + CHICKEN CURRY','non-veg',299,'{}'::jsonb,'',5,true),
('happy','happy hours food','COMBO','2 BUTTER NAAN + MIX VEG CURRY','veg',299,'{}'::jsonb,'',6,true),
('happy','happy hours food','COMBO','2 ROTI + PANEER BUTTER MASALA','veg',299,'{}'::jsonb,'',7,true),
('happy','happy hours drinks','LIQUOR','KINGFISHER ULTRA','alcoholic',199,'{}'::jsonb,'',0,true),
('happy','happy hours drinks','LIQUOR','BUDWEISER','alcoholic',199,'{}'::jsonb,'',1,true),
('happy','happy hours drinks','LIQUOR','HEINEKEN','alcoholic',199,'{}'::jsonb,'',2,true),
('happy','happy hours drinks','LIQUOR','BACARDI WHITE RUM','alcoholic',199,'{}'::jsonb,'',3,true),
('happy','happy hours drinks','LIQUOR','OLD MONK RUM','alcoholic',199,'{}'::jsonb,'',4,true),
('happy','happy hours drinks','LIQUOR','GREATER THAN GIN','alcoholic',199,'{}'::jsonb,'',5,true),
('happy','happy hours drinks','LIQUOR','TEQUILA 5 AGAVE','alcoholic',199,'{}'::jsonb,'',6,true),
('happy','happy hours drinks','LIQUOR','BLACK & WHITE','alcoholic',199,'{}'::jsonb,'',7,true),
('happy','happy hours drinks','LIQUOR','TEACHERS HIGHLAND','alcoholic',199,'{}'::jsonb,'',8,true),
('happy','happy hours drinks','LIQUOR','100 PIPERS','alcoholic',199,'{}'::jsonb,'',9,true),
('happy','happy hours drinks','LIQUOR','BALENTINE','alcoholic',249,'{}'::jsonb,'',10,true),
('happy','happy hours drinks','LIQUOR','JAMESON','alcoholic',249,'{}'::jsonb,'',11,true),
('happy','happy hours drinks','COCKTAILS','COSMOPOLITAN','alcoholic',199,'{}'::jsonb,'',0,true),
('happy','happy hours drinks','COCKTAILS','DAIQUIRI','alcoholic',199,'{}'::jsonb,'',1,true),
('happy','happy hours drinks','COCKTAILS','MARGARITA','alcoholic',199,'{}'::jsonb,'',2,true),
('happy','happy hours drinks','COCKTAILS','MARTINI FLAVOURED','alcoholic',199,'{}'::jsonb,'',3,true),
('happy','happy hours drinks','COCKTAILS','KAMIKAZE SHOTS','alcoholic',199,'{}'::jsonb,'',4,true),
('happy','happy hours drinks','MOCKTAILS / JUICE','KUKUM KICK','non-alcoholic',199,'{}'::jsonb,'',0,true),
('happy','happy hours drinks','MOCKTAILS / JUICE','LITCH AAM PANNA','non-alcoholic',199,'{}'::jsonb,'',1,true),
('happy','happy hours drinks','MOCKTAILS / JUICE','PASSION PEACH','non-alcoholic',199,'{}'::jsonb,'',2,true),
('happy','happy hours drinks','MOCKTAILS / JUICE','MOJITO','non-alcoholic',199,'{}'::jsonb,'',3,true),
('happy','happy hours drinks','MOCKTAILS / JUICE','WATERMELON','non-alcoholic',199,'{}'::jsonb,'',4,true),
('happy','happy hours drinks','MOCKTAILS / JUICE','PINEAPPLE JUICE','non-alcoholic',199,'{}'::jsonb,'',5,true),
('happy','happy hours drinks','MOCKTAILS / JUICE','FRESH LIME SODA','non-alcoholic',199,'{}'::jsonb,'',6,true);